language: rust
rust:
  - stable
  - beta
  - nightly

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = stable ] &&
  cargo doc --no-deps &&
  echo '<meta http-equiv=refresh content=0;url=marpa/index.html>' > target/doc/index.html &&
  pip install --user ghp-import &&
  /home/travis/.local/bin/ghp-import -n target/doc &&
  git push -fq https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages 

env:
  global:
    - TRAVIS_REPO_SLUG: Pursuit92/marpa
    - secure: "ECh/oeTJ0v07jz9s8STbFvcVQPpueRZEuN1DeoS5/QbEOs4zELiiEAwaeGFO38cOHqcGsEBkxbzSa3cvkWuEX6KVFzTVsf3kptMtyhgBGltaw8a0JzVKRFg7lqGgvCmj9ortn4nrDY5XttA8oO69JkLa2L8cx5C06gss2Wa8tFxF/ejTWWPQXNK9J7yF1LYjhWNtFfUpDy9Pj9+sHBtAAF5sMIu4PN6LZjxTehtncUkH0vCW54KUEPOTFwnonkGoKVdi82HgYKbmzm7WAJ46cXZiSw1ydVJOZpjwpPvjkNpQZNv0xRApixSfq2Hr9tYWw1R7184TwlI175gfh3l3VPLQJBBlc0LrK2pdGLzQguEvoGe1QqsxrBZibbwNWvJasJUCvBvxpMUFW7aEhIEOFxZp/KDN1FWms8UWJZGhvoLoA+yEj8Rah6fgN2WzGfNRiCW6sN2PWTsabT3HdGZQSlZzYnUJsIh+DUk7r2VuwN9YiL7ZAfZCRWgHl13cvYx6FoXobNO9Jd4HXVrhjvlakFk8sB56Gt6QD24O/8BNM6rrP5j5sy7lprgOCvheXVYbcYW8vje9KWe1dCN/OyMQWvBYWrccnrpjlmWmymebs5r6flfVRX4GmIwT0EC+bmJ8KJlDv5wIBgUMnsmNIOapqT43PXcvkg91OWcGXjXgLNM="