[package]
name = "marpa"
version = "0.1.4"
authors = ["Josh Chase <jcjoshuachase@gmail.com>"]
description = "Safe bindings to the libmarpa parsing engine"
license = "MIT"
repository = "https://github.com/Pursuit92/marpa"
documentation = "https://pursuit92.github.io/marpa"

[dependencies]
libc = "*"
regex = "*"
regex-syntax = "0.2.2"
libmarpa-sys = "0.1.2"
